"""
Tourism Experience Analytics - Streamlit Application
=====================================================

This application is the presentation/deployment layer for the Tourism Experience
Analytics project. It exposes the three machine-learning objectives required by
the project brief:

1. Classification  -> predict a user's likely Visit Mode.
2. Regression      -> predict the rating a user may give an attraction.
3. Recommendation  -> return a ranked list of attractions for known and new users.

It also exposes EDA, model-evaluation, and SQL analytics so the application can
serve as a complete local project demonstration.

Run locally from the project root with:
    streamlit run app.py

Important:
- This file expects the processed datasets, trained models, metrics, and SQLite
  database that are generated by `python run_pipeline.py`.
- The application intentionally uses cached loaders so large files and models are
  not reloaded every time a Streamlit widget changes.
"""

from __future__ import annotations
from src.config import DB_DIR, METRICS_DIR, MODELS_DIR, PROCESSED_DIR

import json
import sqlite3
import sys
from pathlib import Path

import joblib
import pandas as pd
import plotly.express as px
import streamlit as st

# -----------------------------------------------------------------------------
# 1. PROJECT PATH SETUP
# -----------------------------------------------------------------------------
# `ROOT` is the folder that contains app.py. Adding it to sys.path makes imports
# such as `from src.config import ...` reliable whether Streamlit is started from
# VS Code, Command Prompt, or PowerShell.
ROOT = Path(__file__).resolve().parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

# Centralized directory definitions used throughout the project.


# -----------------------------------------------------------------------------
# 2. STREAMLIT PAGE CONFIGURATION
# -----------------------------------------------------------------------------
st.set_page_config(
    page_title="Tourism Experience Analytics",
    page_icon="🌍",
    layout="wide",
    initial_sidebar_state="expanded",
)


# -----------------------------------------------------------------------------
# 3. CACHED DATA / MODEL LOADERS
# -----------------------------------------------------------------------------
@st.cache_data(show_spinner=False)
def load_data() -> tuple[pd.DataFrame, pd.DataFrame]:
    """Load the two processed datasets used by the application.

    Returns
    -------
    df:
        Cleaned and consolidated historical transaction dataset. It contains
        transaction, user-demographic, visit-mode, and attraction information.
    catalog:
        Cleaned expanded attraction catalog used by the recommendation system.
    """
    df = pd.read_csv(PROCESSED_DIR / "tourism_merged_clean.csv")
    catalog = pd.read_csv(PROCESSED_DIR / "attraction_catalog_clean.csv")
    return df, catalog


@st.cache_resource(show_spinner=False)
def load_models():
    """Load trained ML/recommendation artifacts once per Streamlit session."""
    classification = joblib.load(
        MODELS_DIR / "best_classification_model.joblib")
    label_encoder = joblib.load(MODELS_DIR / "visit_mode_label_encoder.joblib")
    regression = joblib.load(MODELS_DIR / "best_regression_model.joblib")
    recommender = joblib.load(MODELS_DIR / "hybrid_recommender.joblib")
    return classification, label_encoder, regression, recommender


@st.cache_data(show_spinner=False)
def load_metrics() -> tuple[dict, dict, dict]:
    """Load test/evaluation metrics produced by the training pipeline."""
    with open(METRICS_DIR / "classification_test_metrics.json", encoding="utf-8") as f:
        cls = json.load(f)

    with open(METRICS_DIR / "regression_test_metrics.json", encoding="utf-8") as f:
        reg = json.load(f)

    with open(METRICS_DIR / "recommendation_metrics.json", encoding="utf-8") as f:
        rec = json.load(f)

    return cls, reg, rec


# -----------------------------------------------------------------------------
# 4. SMALL REUSABLE UI HELPERS
# -----------------------------------------------------------------------------
def unique_values(data: pd.DataFrame, column: str) -> list[str]:
    """Return sorted, non-null string values for a Streamlit select box."""
    return sorted(data[column].dropna().astype(str).unique().tolist())


def geography_inputs(data: pd.DataFrame, prefix: str) -> tuple[str, str, str, str]:
    """Collect a *consistent* user geography from observed dataset combinations.

    The original app used four independent dropdowns. That allowed impossible
    combinations such as Asia + United States + London. Cascading filters below
    keep the selected continent, region, country, and city consistent with real
    rows in the supplied dataset, which is safer for ML inference.
    """
    geo = data[["UserContinent", "UserRegion",
                "UserCountry", "UserCityName"]].drop_duplicates()

    continent = st.selectbox(
        "User continent",
        sorted(geo["UserContinent"].dropna().astype(str).unique()),
        key=f"{prefix}_continent",
    )

    region_options = sorted(
        geo.loc[geo["UserContinent"].astype(str) == continent, "UserRegion"]
        .dropna()
        .astype(str)
        .unique()
    )
    region = st.selectbox("User region", region_options,
                          key=f"{prefix}_region")

    country_options = sorted(
        geo.loc[
            (geo["UserContinent"].astype(str) == continent)
            & (geo["UserRegion"].astype(str) == region),
            "UserCountry",
        ]
        .dropna()
        .astype(str)
        .unique()
    )
    country = st.selectbox(
        "User country", country_options, key=f"{prefix}_country")

    city_options = sorted(
        geo.loc[
            (geo["UserContinent"].astype(str) == continent)
            & (geo["UserRegion"].astype(str) == region)
            & (geo["UserCountry"].astype(str) == country),
            "UserCityName",
        ]
        .dropna()
        .astype(str)
        .unique()
    )
    city = st.selectbox("User city", city_options, key=f"{prefix}_city")

    return continent, region, country, city


def attraction_inputs(data: pd.DataFrame, prefix: str) -> tuple[str, str, str, str]:
    """Collect one historical attraction and its model feature values.

    The attraction metadata comes from the processed historical dataset so the
    exact feature names match the data used when the models were trained.
    """
    attractions = (
        data[["Attraction", "AttractionTypeLabel",
              "AttractionCityName", "AttractionCountry"]]
        .drop_duplicates("Attraction")
        .sort_values("Attraction")
    )

    name = st.selectbox(
        "Attraction",
        attractions["Attraction"].tolist(),
        key=f"{prefix}_attraction",
    )
    row = attractions.loc[attractions["Attraction"] == name].iloc[0]

    st.caption(
        "Model metadata — "
        f"Type: {row.AttractionTypeLabel} · "
        f"City label: {row.AttractionCityName} · "
        f"Country label: {row.AttractionCountry}"
    )

    return (
        str(row.Attraction),
        str(row.AttractionTypeLabel),
        str(row.AttractionCityName),
        str(row.AttractionCountry),
    )


def add_rank(result: pd.DataFrame) -> pd.DataFrame:
    """Add an explicit rank column to recommendation output."""
    ranked = result.copy().reset_index(drop=True)
    ranked.insert(0, "Rank", range(1, len(ranked) + 1))
    return ranked


def download_recommendations(result: pd.DataFrame, file_name: str, key: str) -> None:
    """Offer the displayed ranked recommendations as a CSV download."""
    st.download_button(
        "Download recommendations as CSV",
        data=result.to_csv(index=False).encode("utf-8"),
        file_name=file_name,
        mime="text/csv",
        key=key,
    )


# -----------------------------------------------------------------------------
# 5. LOAD PROJECT ARTIFACTS
# -----------------------------------------------------------------------------
try:
    df, catalog = load_data()
    classification_model, visit_mode_encoder, regression_model, recommender = load_models()
    cls_metrics, reg_metrics, rec_metrics = load_metrics()
except FileNotFoundError as exc:
    st.error(
        "A required generated project artifact is missing. "
        "Run `python run_pipeline.py` from the project root and restart Streamlit."
    )
    st.exception(exc)
    st.stop()


# -----------------------------------------------------------------------------
# 6. GLOBAL PAGE HEADER + SIDEBAR NAVIGATION
# -----------------------------------------------------------------------------
st.title("🌍 Tourism Experience Analytics")
st.write(
    "Classification, rating prediction, tourism analytics, SQL analysis, "
    "and personalized attraction recommendations from the supplied tourism dataset."
)

nav = st.sidebar.radio(
    "Navigate",
    [
        "Executive Dashboard",
        "Visit Mode Prediction",
        "Rating Prediction",
        "Recommendations",
        "Model Evaluation",
        "SQL Analytics",
        "Project Notes",
    ],
)

st.sidebar.markdown("---")
st.sidebar.caption(
    "Local Streamlit deployment · Models and metrics are loaded from the project artifacts folder."
)


# =============================================================================
# PAGE A — EXECUTIVE DASHBOARD / EDA
# =============================================================================
if nav == "Executive Dashboard":
    st.subheader("Tourism Analytics Dashboard")
    st.caption(
        "This page summarizes user demographics, visit behavior, ratings, attraction popularity, "
        "geographic patterns, and user segments."
    )

    # ----- High-level KPI cards -----
    k1, k2, k3, k4, k5 = st.columns(5)
    k1.metric("Transactions", f"{len(df):,}")
    k2.metric("Users", f"{df['UserId'].nunique():,}")
    k3.metric("Historical Attractions", f"{df['AttractionId'].nunique():,}")
    k4.metric("Expanded Catalog", f"{catalog['AttractionId'].nunique():,}")
    k5.metric("Average Rating", f"{df['Rating'].mean():.2f} / 5")

    # ----- Core distribution charts -----
    c1, c2 = st.columns(2)
    with c1:
        mode_counts = (
            df["VisitModeName"]
            .value_counts()
            .rename_axis("Visit Mode")
            .reset_index(name="Visits")
        )
        st.plotly_chart(
            px.bar(mode_counts, x="Visit Mode", y="Visits",
                   title="Visit Mode Distribution"),
            use_container_width=True,
        )

    with c2:
        rating_counts = (
            df["Rating"]
            .value_counts()
            .sort_index()
            .rename_axis("Rating")
            .reset_index(name="Transactions")
        )
        st.plotly_chart(
            px.bar(rating_counts, x="Rating", y="Transactions",
                   title="Rating Distribution"),
            use_container_width=True,
        )

    # ----- Time trend + most popular attractions -----
    c3, c4 = st.columns(2)
    with c3:
        yearly = df.groupby("VisitYear").size().reset_index(name="Visits")
        st.plotly_chart(
            px.line(yearly, x="VisitYear", y="Visits",
                    markers=True, title="Visits by Year"),
            use_container_width=True,
        )

    with c4:
        top = (
            df.groupby("Attraction")
            .size()
            .nlargest(10)
            .sort_values()
            .reset_index(name="Visits")
        )
        st.plotly_chart(
            px.bar(top, x="Visits", y="Attraction",
                   orientation="h", title="Top 10 Attractions"),
            use_container_width=True,
        )

    # ----- Explicit user-demographic EDA requested in the project brief -----
    st.markdown("#### User Geography")
    g1, g2 = st.columns(2)

    with g1:
        continent_counts = (
            df.groupby("UserContinent")
            .size()
            .sort_values(ascending=False)
            .reset_index(name="Visits")
        )
        st.plotly_chart(
            px.bar(
                continent_counts,
                x="UserContinent",
                y="Visits",
                title="User Distribution by Continent",
            ),
            use_container_width=True,
        )

    with g2:
        region_counts = (
            df.groupby("UserRegion")
            .size()
            .nlargest(12)
            .sort_values()
            .reset_index(name="Visits")
        )
        st.plotly_chart(
            px.bar(
                region_counts,
                x="Visits",
                y="UserRegion",
                orientation="h",
                title="Top User Regions",
            ),
            use_container_width=True,
        )

    # Plotly can map country names directly, so no latitude/longitude file is required.
    country_counts = df.groupby(
        "UserCountry").size().reset_index(name="Visits")
    st.plotly_chart(
        px.choropleth(
            country_counts,
            locations="UserCountry",
            locationmode="country names",
            color="Visits",
            hover_name="UserCountry",
            title="Global User Distribution by Country",
        ),
        use_container_width=True,
    )

    # ----- Relationship requested by the brief: VisitMode vs user demographics -----
    st.markdown("#### Visit Mode and Demographic Relationship")
    segment = (
        df.groupby(["UserContinent", "VisitModeName"])
        .size()
        .reset_index(name="Visits")
    )
    st.plotly_chart(
        px.bar(
            segment,
            x="UserContinent",
            y="Visits",
            color="VisitModeName",
            barmode="group",
            title="Visit Mode by User Continent",
        ),
        use_container_width=True,
    )

    # ----- Attraction popularity vs satisfaction -----
    type_stats = (
        df.groupby("AttractionTypeLabel")
        .agg(Visits=("TransactionId", "count"), Average_Rating=("Rating", "mean"))
        .reset_index()
    )
    st.plotly_chart(
        px.scatter(
            type_stats,
            x="Visits",
            y="Average_Rating",
            size="Visits",
            hover_name="AttractionTypeLabel",
            title="Attraction Type: Popularity vs Satisfaction",
        ),
        use_container_width=True,
    )

    st.info(
        "The dashboard uses the cleaned consolidated historical dataset. "
        "The expanded attraction catalog is used by the recommendation system."
    )


# =============================================================================
# PAGE B — CLASSIFICATION: VISIT MODE PREDICTION
# =============================================================================
elif nav == "Visit Mode Prediction":
    st.subheader("Classification — Predict User Visit Mode")
    st.caption(
        "Target classes: Business, Couples, Family, Friends, and Solo. "
        "Rating is intentionally excluded because a pre-visit prediction should not use a future rating."
    )

    # Demographic inputs are constrained to combinations observed in the data.
    continent, region, country, city = geography_inputs(df, "cls")

    c1, c2 = st.columns(2)
    with c1:
        year = st.selectbox(
            "Visit year",
            sorted(df["VisitYear"].dropna().astype(
                int).unique().tolist(), reverse=True),
            key="cls_year",
        )
    with c2:
        month = st.slider("Visit month", 1, 12, 8, key="cls_month")

    attraction, attr_type, attr_city, attr_country = attraction_inputs(
        df, "cls")

    if st.button("Predict Visit Mode", type="primary"):
        # Build a one-row DataFrame with EXACTLY the feature names expected by the
        # trained sklearn/XGBoost pipeline.
        row = pd.DataFrame(
            [
                {
                    "UserContinent": continent,
                    "UserRegion": region,
                    "UserCountry": country,
                    "UserCityName": city,
                    "VisitYear": year,
                    "VisitMonth": month,
                    "Attraction": attraction,
                    "AttractionTypeLabel": attr_type,
                    "AttractionCityName": attr_city,
                    "AttractionCountry": attr_country,
                }
            ]
        )

        # The classifier returns an encoded class. Convert it back to the human-
        # readable visit-mode label and display the probability distribution.
        pred_code = classification_model.predict(row)[0]
        probabilities = classification_model.predict_proba(row)[0]
        label = visit_mode_encoder.inverse_transform([pred_code])[0]

        st.success(f"Predicted visit mode: **{label}**")

        prob_df = pd.DataFrame(
            {
                "Visit Mode": visit_mode_encoder.classes_,
                "Probability": probabilities,
            }
        ).sort_values("Probability", ascending=False)

        st.plotly_chart(
            px.bar(
                prob_df,
                x="Visit Mode",
                y="Probability",
                title="Prediction Probabilities",
                range_y=[0, 1],
            ),
            use_container_width=True,
        )

        st.caption(
            "Interpret the probabilities as model confidence, not certainty. "
            "The held-out classification performance is shown on the Model Evaluation page."
        )


# =============================================================================
# PAGE C — REGRESSION: RATING PREDICTION
# =============================================================================
elif nav == "Rating Prediction":
    st.subheader("Regression — Predict Attraction Rating")
    st.caption(
        "The regression model estimates a user's expected rating on the 1–5 scale.")

    continent, region, country, city = geography_inputs(df, "reg")

    c1, c2, c3 = st.columns(3)
    with c1:
        year = st.selectbox(
            "Visit year",
            sorted(df["VisitYear"].dropna().astype(
                int).unique().tolist(), reverse=True),
            key="reg_year",
        )
    with c2:
        month = st.slider("Visit month", 1, 12, 8, key="reg_month")
    with c3:
        visit_mode = st.selectbox(
            "Visit mode",
            unique_values(df, "VisitModeName"),
            key="reg_mode",
        )

    attraction, attr_type, attr_city, attr_country = attraction_inputs(
        df, "reg")

    if st.button("Predict Rating", type="primary"):
        row = pd.DataFrame(
            [
                {
                    "UserContinent": continent,
                    "UserRegion": region,
                    "UserCountry": country,
                    "UserCityName": city,
                    "VisitYear": year,
                    "VisitMonth": month,
                    "Attraction": attraction,
                    "AttractionTypeLabel": attr_type,
                    "AttractionCityName": attr_city,
                    "AttractionCountry": attr_country,
                    "VisitModeName": visit_mode,
                }
            ]
        )

        # Clip the numerical prediction to the valid project rating range.
        prediction = float(regression_model.predict(row)[0])
        prediction = max(1.0, min(5.0, prediction))

        st.success(f"Predicted rating: **{prediction:.2f} / 5.00**")
        st.progress(prediction / 5.0)
        st.caption(
            "Use this result as an estimated satisfaction signal. "
            "The regression test metrics are shown on the Model Evaluation page."
        )


# =============================================================================
# PAGE D — RECOMMENDATION SYSTEM
# =============================================================================
elif nav == "Recommendations":
    st.subheader("Recommendation System — Ranked Attraction Suggestions")
    st.caption(
        "The project supports collaborative filtering, content-based filtering, "
        "an optional hybrid strategy, and cold-start recommendations."
    )

    known_tab, cold_tab = st.tabs(
        ["Known User / History-Based", "New User / Cold Start"])

    # ----- Known user: recommendation based on stored historical interactions -----
    with known_tab:
        user_ids = sorted(df["UserId"].dropna().astype(int).unique().tolist())
        user_id = st.selectbox("User ID", user_ids, key="rec_user")

        # Show that user history really is part of the recommendation workflow.
        user_history = (
            df.loc[df["UserId"].astype(int) == int(user_id),
                   ["VisitYear", "VisitMonth", "VisitModeName", "Attraction", "Rating"]]
            .sort_values(["VisitYear", "VisitMonth"], ascending=False)
        )
        with st.expander("View this user's historical visits used by the recommender"):
            st.dataframe(user_history, use_container_width=True,
                         hide_index=True)

        strategy = st.selectbox(
            "Recommendation strategy",
            ["content", "hybrid", "collaborative"],
            index=0,
            help=(
                "Content uses attraction similarity; collaborative uses historical rating patterns; "
                "hybrid combines content, collaborative, and popularity signals."
            ),
        )
        k = st.slider("Number of recommendations", 5, 20, 10, key="rec_k")

        if st.button("Recommend for User", type="primary", key="known_rec_button"):
            result = recommender.recommend_known_user(
                user_id, k=k, strategy=strategy)
            result = add_rank(result)

            st.success(
                f"Top {len(result)} ranked attractions for User {user_id}")
            st.dataframe(result, use_container_width=True, hide_index=True)
            download_recommendations(
                result, f"recommendations_user_{user_id}.csv", "known_download")

            st.caption(
                "Content and hybrid modes can recommend from the expanded catalog. "
                "Pure collaborative evidence exists only for attractions with historical transactions."
            )

    # ----- New user: preference-based recommendations when no history exists -----
    with cold_tab:
        types = [
            "Any"] + sorted(catalog["AttractionTypeBroad"].dropna().astype(str).unique())
        countries = [
            "Any"] + sorted(catalog["AttractionCountry"].dropna().astype(str).unique())
        cities = [
            "Any"] + sorted(catalog["AttractionCityName"].dropna().astype(str).unique())
        modes = ["Any"] + unique_values(df, "VisitModeName")

        c1, c2 = st.columns(2)
        with c1:
            pref_type = st.selectbox(
                "Preferred attraction type", types, key="cold_type")
            pref_country = st.selectbox(
                "Preferred destination country", countries, key="cold_country")
        with c2:
            pref_city = st.selectbox(
                "Preferred destination city", cities, key="cold_city")
            pref_mode = st.selectbox(
                "Preferred visit mode", modes, key="cold_mode")

        k2 = st.slider("Number of recommendations", 5, 20, 10, key="cold_k")

        if st.button("Generate Cold-Start Recommendations", type="primary", key="cold_rec_button"):
            result = recommender.recommend_cold_start(
                pref_type,
                pref_country,
                pref_city,
                pref_mode,
                k=k2,
            )
            result = add_rank(result)

            st.success(
                f"Top {len(result)} ranked attractions for the selected preferences")
            st.dataframe(result, use_container_width=True, hide_index=True)
            download_recommendations(
                result, "cold_start_recommendations.csv", "cold_download")


# =============================================================================
# PAGE E — MODEL EVALUATION
# =============================================================================
elif nav == "Model Evaluation":
    st.subheader("Model Performance and Comparison")
    st.caption(
        "The project compares multiple algorithms, selects the best model using validation data, "
        "and reports final performance on a held-out test set."
    )

    # ----- Classification metrics required by the brief -----
    st.markdown("#### Classification — Visit Mode")
    c1, c2, c3 = st.columns(3)
    c1.metric("Best model", cls_metrics["best_model"])
    c2.metric("Accuracy", f"{cls_metrics['accuracy']:.3f}")
    c3.metric("Weighted F1", f"{cls_metrics['f1_weighted']:.3f}")

    c4, c5, c6 = st.columns(3)
    c4.metric("Weighted Precision", f"{cls_metrics['precision_weighted']:.3f}")
    c5.metric("Weighted Recall", f"{cls_metrics['recall_weighted']:.3f}")
    c6.metric("Macro F1", f"{cls_metrics['f1_macro']:.3f}")

    cls_comp = pd.read_csv(METRICS_DIR / "classification_model_comparison.csv")
    st.dataframe(cls_comp, use_container_width=True, hide_index=True)

    # ----- Regression metrics required by the brief -----
    st.markdown("#### Regression — Rating")
    r1, r2, r3 = st.columns(3)
    r1.metric("Best model", reg_metrics["best_model"])
    r2.metric("RMSE", f"{reg_metrics['rmse']:.3f}")
    r3.metric("MSE", f"{reg_metrics['mse']:.3f}")

    r4, r5 = st.columns(2)
    r4.metric("MAE", f"{reg_metrics['mae']:.3f}")
    r5.metric("R²", f"{reg_metrics['r2']:.3f}")

    reg_comp = pd.read_csv(METRICS_DIR / "regression_model_comparison.csv")
    st.dataframe(reg_comp, use_container_width=True, hide_index=True)

    # ----- Recommendation-system evaluation -----
    st.markdown("#### Recommendation")
    q1, q2 = st.columns(2)
    q1.metric("Collaborative RMSE", f"{rec_metrics['collaborative_rmse']:.3f}")
    q2.metric("Relevant hold-out cases evaluated for MAP",
              f"{rec_metrics['map_evaluated_relevant_users']:,}")

    map_df = pd.DataFrame(
        {
            "Strategy": ["Collaborative", "Content-Based", "Hybrid"],
            "MAP@10": [
                rec_metrics["map_at_10_collaborative"],
                rec_metrics["map_at_10_content"],
                rec_metrics["map_at_10_hybrid"],
            ],
        }
    )
    st.plotly_chart(
        px.bar(map_df, x="Strategy", y="MAP@10",
               title="Recommendation MAP@10 Comparison"),
        use_container_width=True,
    )
    st.dataframe(map_df, use_container_width=True, hide_index=True)

    st.warning(
        "The predictive signal is useful but not strong enough to treat predictions as certainty. "
        "Classification is imbalanced and rating R² is modest; use predictions as decision-support signals."
    )


# =============================================================================
# PAGE F — SQL ANALYTICS
# =============================================================================
elif nav == "SQL Analytics":
    st.subheader("SQL Tourism Analytics")
    st.caption(
        "These saved analytical queries run against the local SQLite database generated by the data pipeline."
    )

    queries = {
        "Top Attractions": """
            SELECT Attraction,
                   COUNT(*) AS Visits,
                   ROUND(AVG(Rating), 3) AS AvgRating
            FROM tourism_analytics
            GROUP BY Attraction
            ORDER BY Visits DESC
            LIMIT 15
        """,
        "Visit Modes": """
            SELECT VisitModeName,
                   COUNT(*) AS Visits,
                   ROUND(AVG(Rating), 3) AS AvgRating
            FROM tourism_analytics
            GROUP BY VisitModeName
            ORDER BY Visits DESC
        """,
        "User Continents": """
            SELECT UserContinent,
                   COUNT(*) AS Visits,
                   ROUND(AVG(Rating), 3) AS AvgRating
            FROM tourism_analytics
            GROUP BY UserContinent
            ORDER BY Visits DESC
        """,
        "Top User Regions": """
            SELECT UserRegion,
                   COUNT(*) AS Visits,
                   ROUND(AVG(Rating), 3) AS AvgRating
            FROM tourism_analytics
            GROUP BY UserRegion
            ORDER BY Visits DESC
            LIMIT 20
        """,
        "Top User Countries": """
            SELECT UserCountry,
                   COUNT(*) AS Visits,
                   ROUND(AVG(Rating), 3) AS AvgRating
            FROM tourism_analytics
            GROUP BY UserCountry
            ORDER BY Visits DESC
            LIMIT 20
        """,
        "Attraction Types": """
            SELECT AttractionTypeLabel,
                   COUNT(*) AS Visits,
                   ROUND(AVG(Rating), 3) AS AvgRating
            FROM tourism_analytics
            GROUP BY AttractionTypeLabel
            ORDER BY Visits DESC
        """,
        "Visit Mode by Continent": """
            SELECT UserContinent,
                   VisitModeName,
                   COUNT(*) AS Visits,
                   ROUND(AVG(Rating), 3) AS AvgRating
            FROM tourism_analytics
            GROUP BY UserContinent, VisitModeName
            ORDER BY UserContinent, Visits DESC
        """,
        "Year Trend": """
            SELECT VisitYear,
                   COUNT(*) AS Visits,
                   ROUND(AVG(Rating), 3) AS AvgRating
            FROM tourism_analytics
            GROUP BY VisitYear
            ORDER BY VisitYear
        """,
    }

    selected = st.selectbox("Saved analysis query", list(queries))
    sql = queries[selected].strip()
    st.code(sql, language="sql")

    with sqlite3.connect(DB_DIR / "tourism.db") as connection:
        result = pd.read_sql_query(sql, connection)

    st.dataframe(result, use_container_width=True, hide_index=True)


# =============================================================================
# PAGE G — PROJECT NOTES / DATA-QUALITY DISCLOSURE
# =============================================================================
elif nav == "Project Notes":
    st.subheader("Project Coverage and Interpretation Notes")

    st.markdown(
        """
        **Implemented project objectives**

        - **Classification:** predict Visit Mode using user demographics, visit timing, and attraction features.
        - **Regression:** predict the expected 1–5 attraction rating.
        - **Recommendation:** return a ranked list using collaborative, content-based, hybrid, and cold-start methods.
        - **Analytics:** EDA, visualization, SQL analysis, model comparison, and business-facing outputs.
        - **Deployment:** local Streamlit application using saved trained artifacts.
        """
    )

    st.markdown("#### Data-quality note")
    st.info(
        "The supplied attraction records contain location-ID metadata that is not fully consistent with some "
        "human-readable attraction addresses. The data pipeline preserves the supplied IDs/lookup behavior for "
        "reproducibility. Therefore, attraction location labels should be interpreted as source metadata rather "
        "than independently verified geolocation. User geography is based on the supplied user lookup tables."
    )

    st.markdown("#### Current held-out results")
    results = pd.DataFrame(
        {
            "Component": ["Classification", "Regression", "Recommendation"],
            "Selected / Best": [
                cls_metrics["best_model"],
                reg_metrics["best_model"],
                "Content-Based MAP@10",
            ],
            "Key Result": [
                f"Accuracy {cls_metrics['accuracy']:.3f}; weighted F1 {cls_metrics['f1_weighted']:.3f}",
                f"RMSE {reg_metrics['rmse']:.3f}; R² {reg_metrics['r2']:.3f}",
                f"MAP@10 {rec_metrics['map_at_10_content']:.3f}",
            ],
        }
    )
    st.dataframe(results, use_container_width=True, hide_index=True)

    st.caption(
        "For full methodology, cleaning details, limitations, business insights, and reproducibility steps, "
        "see the README and final project report in the docs folder."
    )
